name: Uses latest CS:GO version

on:
  # Run at 37 minutes past every hour
  schedule:
    - cron: '37 * * * *'
  # Enable run manually
  workflow_dispatch:

env:
  DOCKER_REPO: 'theobrown/csgo-get5-docker'

jobs:
  check-csgo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch metadata from DockerHub
        id: fetch-metadata
        uses: theo-brown/fetch-dockerhub-metadata@v1
        with:
          repository: ${{ env.DOCKER_REPO }}
          tag: latest
      - name: Get installed CSGO version from metadata
        id: csgo-version
        run: |
          INSTALLED_VERSION=$(echo '${{ steps.fetch-metadata.outputs.labels }}' | jq '.csgo_version | tonumber')
          echo "CSGO version installed on DockerHub: $INSTALLED_VERSION"
          echo "::set-output name=version::$INSTALLED_VERSION"
      - name: Check CSGO version against Steam API
        run: |
          VERSION_CHECK=$(curl -s "http://api.steampowered.com/ISteamApps/UpToDateCheck/v1?appid=730&version=${{ steps.csgo-version.outputs.version }}" | jq .response)
          if [ $(echo $VERSION_CHECK | jq .up_to_date) = true ]
          then
            echo "$DOCKER_REPO:latest contains the latest CS:GO version (${{ steps.csgo-version.outputs.version }})."
            exit 0
          else
            echo "::error::$DOCKER_REPO:latest contains an outdated CS:GO version \
                  (installed: ${{ steps.csgo-version.outputs.version }} / latest: $(echo $VERSION_CHECK | jq .required_version))."
          fi
